translations = {
    'ar': {
        "maintenance_False":"تعطيل وضع الصيانه", 
        "maintenance_True":"تفعيل وضع الصيانه", 
        "spam_issue":"الرقم محظور سبام تم رفضه!!!!!! ", 
        "show_balance": "عرض الرصيد",
        "balance_info": "سيتم إضافة {balance} إلى رصيدك لهذا الرقم",
        "invalid_2fa_password":"تم ادخال التحقق بخطوتين بشكل خاطئء اعد المحاوله الان", 
        "balance_added":"🎉تمت إضافة الرقم بنجاح {number} \n\nأنا جاهز الآن لاستلام المزيد من الأرقام، إذا احتجت إلى أي شيء أرسل /help", 
        'too_many_sessions': "لا تزال هناك جلسات متبقية، تم إلغاء العملية. أعد إضافة الرقم من جديد", 
        "starting_verification": "بدء التحقق", 
        "please_wait": "انتظر قليلاً جاري المعالجة......", 
        'get_remaining_time': 'عرض الوقت المتبقي', 
        "gift": "فحص مميز", 
        'select_language': 'اختر اللغة المفضلة للبوت:',
        'welcome': 'أهلاً بك',
        'cancel': 'إلغاء',
        'send_number': 'ارسل الرقم.',
        'send_code': 'تم طلب الكود للرقم {number}.\n\nأرسل الكود الآن أو أرسل "الغاء" لإلغاء العملية.',
        
        'send_password': '🔑 أدخل كلمة المرور الخاصة بالرقم {number} أو التحقق بخطوتين.',
        'number_exists': 'الرقم موجود بالفعل.',
        'invalid_number': 'خطأ في الرقم.',
        'invalid_code': 'الكود غير صحيح.',
        'expired_code': 'الكود منتهي الصلاحية، حاول مجددًا.',
        'delete_number': 'تم حذف الرقم بنجاح.',
        'fetch_session': 'جلب ملف الجلسة',
        'no_numbers': 'لا تمتلك أي أرقام حاليًا.',
        'choose_number': 'إليك أرقامك، اختر الرقم الذي تريد حذفه.',
        'language_set': 'تم اختيار اللغة بنجاح!',
        'add_country': 'إضافة دولة',
        'country_list': 'قائمة الدول',
        'country_not_supported': 'لا نقوم بشراء أرقام من هذه الدولة حاليًا.',
        'enter_country_name': 'أدخل اسم الدولة:',
        'enter_country_code': 'أدخل رمز الدولة:',
        'enter_country_price': 'أدخل سعر الشراء بالدولار:',
        'enter_hours': 'أدخل عدد الساعات قبل التحقق:',
        'country_added': 'تمت إضافة الدولة بنجاح!',
        'show_countries': 'عرض الدول المسجلة',
        'no_countries': 'لا توجد دول مسجلة حاليًا.',
        'delete_country': 'حذف دولة',
        'country_deleted': 'تم حذف الدولة بنجاح!',
        'choose_country_to_delete': 'اختر الدولة التي تريد حذفها:',
        'country_not_found': 'الدولة غير موجودة.',
        'ban_user_button': 'حظر مستخدم',
        'unban_user_button': 'إلغاء حظر مستخدم',
        'cancelled': 'تم إلغاء العملية.',
        'confirm': 'تأكيد',
        'balance': 'رصيدك الحالي هو:',
        "yes": "نعم",
        "no": "لا",
        "confirm_delete": "هل تريد حقاً حذف {country_name}؟",
        "delete_cancelled": "تم إلغاء الحذف.",
        "country_deleted": "تم حذف {country_name}.",
        "no_countries": "لا توجد دول لحذفها.",
        "country_not_supported": "هذا الإجراء غير مدعوم لدولتك.",
        "view_pending_numbers": "الأرقام قيد التنفيذ",
        "no_pending_numbers": "لم يتم تسجيل أي أرقام حتى الآن",
        "idbc": "خصم رصيد", 
        "ax": "إضافة رصيد",
        "send_country_numbers": "جلب أرقام الدولة",
        "send_country_code": "أرسل رمز الدولة",
        
        'number_added': 'تمت إضافة الرقم بنجاح.\nعندما ينتهي الوقت ستحصل على 👇',
        'end_sessions': 'عليك إنهاء جميع الجلسات ما عدا جلسة البوت.',
        'operation_cancelled': 'تم إلغاء العملية.',
        'timeout_error': 'انتهت المهلة.',
        'unsupported_number': 'الرقم غير مدعوم.',
        'code_numbers_only': 'الكود يجب أن يكون أرقام فقط.',
        'code_five_digits': 'الكود يجب أن يتكون من 5 أرقام.',
        'api_or_number_error': 'خطأ في API أو الرقم غير صحيح.',
        'error_fetching_sessions': 'خطأ في جلب الجلسات.',
        'sessions_correct': 'تم إنهاء الجلسات بنجاح.',
        'invalid_or_expired_code': 'الكود المدخل غير صالح أو منتهي الصلاحية.',
        "enter_time_format": "المدة بهذا الشكل: \n عدد الساعات \n عدد الدقائق \n عدد الثواني",
        'end_sessions_retry': 'عليك إنهاء الجلسات وإعادة المحاولة.',
        'password_correct': 'تم إدخال كلمة المرور الصحيحة.',
        'unknown_error': 'حدث خطأ غير معروف.', 
        'show_remaining_time': 'عرض الوقت المتبقي',
        'remaining_time': 'الوقت المتبقي: {time} ثانية', 
        'time_elapsed': 'انتهى الوقت',
        'number_not_found': 'الرقم غير موجود',
        'number_already_registered': '🚫 تم تسجيل الرقم {number} مسبقًا.',
        'number_pending_verification': '🚫 تم إرسال الرقم {number} مسبقًا وهو في وقت التحقق.',
        'maintenance_mode_enabled': 'تم تفعيل وضع الصيانة بنجاح.',
        'maintenance_mode_disabled': 'تم تعطيل وضع الصيانة بنجاح.',
        'maintenance_mode_already_enabled': 'البوت في وضع الصيانة بالفعل.',
        'maintenance_mode_already_disabled': 'البوت ليس في وضع الصيانة.',
        'maintenance_mode_active': 'البوت في وضع الصيانة حالياً. يرجى المحاولة مرة أخرى لاحقاً.',
        'data_not_present': 'بياناتك غير موجودة في قاعدة البيانات. أرسل /start وحاول مرة أخرى.',
        'no_permission': 'ليس لديك صلاحية.',
        'send_user_id_ban': 'أرسل معرف المستخدم أو ID الخاص به لحظره.',
        'user_banned_success': 'تم حظر المستخدم {user_id} بنجاح.',
        'user_already_banned': 'المستخدم {user_id} محظور بالفعل.',
        'send_user_id_unban': 'أرسل معرف المستخدم أو ID الخاص به لإلغاء حظره.',
        'user_unbanned_success': 'تم إلغاء حظر المستخدم {user_id} بنجاح.',
        'user_not_banned': 'المستخدم {user_id} غير محظور.',
        'enter_balance_to_add': 'كم تريد إضافة رصيد؟',
        'enter_balance_to_deduct': 'كم تريد خصم رصيد؟',
        'invalid_amount': 'مبلغ غير صالح، الرجاء المحاولة مرة أخرى.',
        'balance_added_success': 'تمت إضافة {amount} $ إلى رصيد المستخدم {user_id}.',
        'balance_deducted_success': 'تم خصم {amount} $ من رصيد المستخدم {user_id}.',
        'balance_added_by_owner': 'تم إضافته بواسطة المالك.',
        'invalid_price': 'سعر غير صالح، الرجاء المحاولة مرة أخرى.',
        'invalid_format': 'تنسيق غير صالح، الرجاء المحاولة مرة أخرى.',
        'invalid_input': 'إدخال غير صالح، الرجاء المحاولة مرة أخرى.',
        'enter_max_numbers': 'ادخل عدد الارقام المطلوب شرائها',
        'enable_spam_check': 'هل تريد تفعيل فحص الاسبام لهذه الدولة؟\nأرسل: نعم أو لا',
        'timeout': 'انتهت المهلة.',
        'help_message': 'يمكنك التواصل مع المالك أو استخدام أحد الخيارات أدناه\n@Alazaizy\n⚪إذا كنت تريد إضافة حساب، أنا جاهز لاستلامه. يمكنك إرساله\nملاحظة: سيقوم نظامنا بالتحقق من أي حساب تقوم بإعادة تعيينه، ولن يتم إضافة الرصيد إليك، وقد يتم حظرك، لذا كن حذراً.\n🟢إذا كنت تريد رصيدك، يجب ألا يكون أقل من 2 دولار في المرسل /coin\n🔵لمعرفة القوانين، أرسل /rules\n⚫لتغيير لغتك، أرسل /language\n\nنعمل دائماً لخدمتك، وستكون المدفوعات فورية إذا قدمت حسابات جيدة الجودة، ولن يتم الدفع لك',
        'continue_help': 'للمتابعة، أرسل رقم الحساب الافتراضي أو أرسل /help للحصول على الإرشادات.',
        
        # أزرار إدارة القادة
        'add_leader': '➕ إضافة قائد',
        'edit_leader': '✏️ تعديل قائد',
        'delete_leader': '🗑️ حذف قائد',
        'show_leader_stats': '📊 إحصائيات قائد',
        'encrypt_leader_stats': '🔒 تشفير إحصائيات',
        
        # رسائل إدارة القادة
        'enter_leader_id': 'أرسل معرف أو يوزر القائد (user_id أو @username):',
        'enter_leader_channel': 'أرسل معرف قناة القائد (channel_id أو @channel):',
        'enter_leader_name': 'أرسل اسم القائد (للمستخدمين):',
        'enter_leader_commission': 'أرسل العمولة على كل رقم (مثال: 0.03):',
        'enter_leader_wallet': 'أرسل عنوان محفظة القائد:',
        'leader_added_success': '✅ تم إضافة القائد \'{name}\' بنجاح!',
        'leader_edited_success': '✅ تم تعديل بيانات القائد بنجاح!',
        'leader_deleted_success': '✅ تم حذف القائد \'{name}\' بنجاح!',
        'no_leaders': '❌ لا توجد قادة مسجلين',
        'leader_not_found': '❌ القائد غير موجود',
        'choose_leader_to_edit': 'اختر القائد المراد تعديله:',
        'choose_leader_to_delete': 'اختر القائد المراد حذفه:',
        'choose_leader_to_show_stats': 'اختر القائد لعرض إحصائياته:',
        'choose_leader_to_encrypt': 'اختر القائد لإعادة تعيين إحصائياته:',
        'enter_new_leader_data': 'أرسل البيانات الجديدة (اسم، معرف قناة، عمولة، عنوان محفظة) كل سطر على حدة:\nاسم القائد\nمعرف القناة\nالعمولة\nعنوان المحفظة',
        'invalid_commission': '❌ العمولة يجب أن تكون رقماً',
        'incomplete_data': '❌ البيانات غير مكتملة',
        'leader_stats_title': '📊 إحصائيات القائد: {name}',
        'leader_withdrawals_count': '🔹 عدد السحوبات: {count}',
        'leader_total_withdrawn': '🔹 إجمالي رصيد السحوبات: ${amount:.2f}',
        'leader_total_commission': '🔹 إجمالي رصيد العمولة: ${amount:.2f}',
        'leader_numbers_count': '🔹 عدد الأرقام المستلمة: {count}',
        'leader_stats_reset': '✅ تم إعادة تعيين إحصائيات القائد \'{name}\' بنجاح!',
        'leader_stats_reset_confirm': 'هل تريد حقاً إعادة تعيين إحصائيات القائد \'{name}\'؟',
        'leader_no_wallet': '❌ القائد غير موجود أو لا يملك عنوان محفظة.',
        'leader_stats_your_title': '📊 إحصائياتك كقائد:',
        'enter_leadername': 'الرجاء إدخال اسم القائد (LEADERNAME):',
        
        # رسائل السحب
        'new_withdrawal_request': 'طلب سحب جديد',
        'your_balance_is': 'رصيدك الحالي هو:',
        'current_time': 'الوقت الحالي:',
        'number_of_added_numbers': 'عدد الأرقام المضافة:',
        'click_button_to_enter_wallet': 'انقر على الزر أدناه للمتابعة بإدخال عنوان محفظتك.',
        'enter_wallet_address': 'إدخال عنوان المحفظة',
        'send_withdrawal_wallet': 'أرسل عنوان محفظة السحب',
        'allowed_wallet_types': 'المسموح: BEP20, LEADERNAME, TRC20',
        'insufficient_balance': 'رصيدك غير كافٍ لإتمام عملية السحب',
        'request_sent_to_owner': 'تم إرسال طلبك إلى المالك',
        'payment_confirmed_successfully': 'تم تأكيد الدفع بنجاح',
        'enter_wallet_address_type': 'الرجاء إدخال عنوان محفظة {wallet_type}:',
        'confirm_withdrawal': 'تأكيد السحب',
        'trx_exchange_error': 'لا يمكن الحصول على سعر صرف TRX الآن. الرجاء المحاولة لاحقاً.',
        'error_processing_request': 'حدث خطأ أثناء معالجة طلبك. الرجاء المحاولة لاحقًا.',
    },
    'en': {
        "maintenance_True":"True maintenance mode", 
        "maintenance_False": "Stop maintenance mode", 
        "spam_issue":"The number has been blocked. Spam has been rejected!!!!!!", 
        "invalid_2fa_password":"Two-step verification was entered incorrectly. Try again now.",  
        "balance_added":"The number {number} was successfully added\n\nI am now ready to receive more numbers. If you need anything, send /help",  
        'too_many_sessions': "There are still sessions remaining. The operation has been cancelled. Re-add the number again", 
        "starting_verification": "starting verification",
        "please_wait": "Wait a little while.....", 
        "gift": "Distinctive examination", 
        'select_language': 'Select your preferred language:',
        'welcome': 'Welcome',
        'cancel': 'Cancel',
        'send_number': 'Send the number.',
        'send_code': 'Code requested for number {number}.\n\nSend the code now or send "cancel" to cancel the process.',
        'session_added': 'Congratulations! The number {number} has been successfully confirmed. A balance of {balance} has been added to your account.',
        'send_password': '🔑 Enter the password for the number {number} or two-factor authentication.',
        'number_exists': 'Number already exists.',
        'invalid_number': 'Invalid number.',
        'invalid_code': 'Invalid code.',
        'expired_code': 'Code expired, try again.',
        'delete_number': 'Number deleted successfully.',
        'fetch_session': 'Fetch session file',
        'no_numbers': 'You currently have no numbers.',
        'choose_number': 'Here are your numbers, select one to delete',
        'language_set': 'Language has been successfully selected!',
        'add_country': 'Add Country',
        'country_list': 'Country List',
        'country_not_supported': 'We do not buy numbers from this country at the moment.',
        'enter_country_name': 'Enter the country name:',
        'enter_country_code': 'Enter the country code:',
        'enter_country_price': 'Enter the purchase price in USD:',
        'enter_hours': 'Enter the number of hours before verification:',
        'country_added': 'Country added successfully!',
        'show_countries': 'Show registered countries',
        'no_countries': 'No countries registered currently.',
        'delete_country': 'Delete Country',
        'country_deleted': 'Country deleted successfully!',
        'choose_country_to_delete': 'Choose a country to delete:',
        'country_not_found': 'Country not found.',
        'cancelled': 'Operation cancelled.',
        'confirm': 'Confirm',
        'balance': 'Your current balance is:',
        "yes": "Yes",
        "no": "No",
        
        'account_invalid': 'Account invalid',
        'show_remaining_time': 'Show remaining time',
        'remaining_time': 'Remaining time: {time} seconds', 
        'time_elapsed': 'Time elapsed',
        'number_not_found': 'Number not found',
        'number_already_registered': '🚫 The number {number} has already been registered.',
        'number_pending_verification': '🚫 The number {number} has been sent previously and is in the verification process.', 
        "confirm_delete": "Do you really want to delete {country_name}?",
        "delete_cancelled": "Deletion cancelled.",
        "country_deleted": "{country_name} has been deleted.",
        "no_countries": "There are no countries to delete.",
        "country_not_supported": "This action is not supported for your country.",
        'ban_user_button': 'Ban User',
        'unban_user_button': 'Unban User',
        "view_pending_numbers": "Numbers are being verified",
        "no_pending_numbers": "No numbers have been recorded yet",
        "idbc": "Add credit", 
        "ax": "Rival credit", 
        "send_country_numbers": "Fetch country numbers",
        "send_country_code": "Send country code",
        
        'number_added': 'Number added successfully.\nWhen time runs out you will get... 👇',
        'end_sessions': 'You need to end all sessions except the bot session.',
        'operation_cancelled': 'Operation cancelled.',
        'timeout_error': 'Timeout error.',
        'unsupported_number': 'Unsupported number.',
        'code_numbers_only': 'The code must be numbers only.',
        'code_five_digits': 'The code must be 5 digits long.',
        'api_or_number_error': 'API error or the number is incorrect.',
        'error_fetching_sessions': 'Error fetching sessions.',
        'sessions_correct': 'Sessions terminated successfully.',
        'invalid_or_expired_code': 'Invalid or expired code.',
        'enter_time_format': 'Time format should be:\nHours\nMinutes\nSeconds',
        'end_sessions_retry': 'End the sessions and try again.',
        'password_correct': 'Correct password entered.',
        'unknown_error': 'An unknown error occurred.',
        'maintenance_mode_enabled': 'Maintenance mode has been enabled successfully.',
        'maintenance_mode_disabled': 'Maintenance mode has been disabled successfully.',
        'maintenance_mode_already_enabled': 'The bot is already in maintenance mode.',
        'maintenance_mode_already_disabled': 'The bot is not in maintenance mode.',
        'maintenance_mode_active': 'The bot is currently in maintenance mode. Please try again later.',
        'data_not_present': 'Your data is not present in the database. Just send /start and try again.',
        'no_permission': 'You do not have permission.',
        'send_user_id_ban': 'Send the user ID or username to ban.',
        'user_banned_success': 'User {user_id} has been banned successfully.',
        'user_already_banned': 'User {user_id} is already banned.',
        'send_user_id_unban': 'Send the user ID or username to unban.',
        'user_unbanned_success': 'User {user_id} has been unbanned successfully.',
        'user_not_banned': 'User {user_id} is not banned.',
        'enter_balance_to_add': 'How much balance do you want to add?',
        'enter_balance_to_deduct': 'How much balance do you want to deduct?',
        'invalid_amount': 'Invalid amount, please try again.',
        'balance_added_success': 'Added {amount} $ to user {user_id} balance.',
        'balance_deducted_success': 'Deducted {amount} $ from user {user_id} balance.',
        'balance_added_by_owner': 'Added by owner.',
        'invalid_price': 'Invalid price, please try again.',
        'invalid_format': 'Invalid format, please try again.',
        'invalid_input': 'Invalid input, please try again.',
        'enter_max_numbers': 'Enter the number of numbers to be purchased',
        'enable_spam_check': 'Do you want to enable spam check for this country?\nSend: Yes or No',
        'timeout': 'Timeout error.',
        'help_message': 'You can contact the owner or use one of the options below\n@Alazaizy\n⚪If you want to add an account, I am ready to receive it. You can send it\nNote: Our system will verify any account you reset, and the balance will not be added to you, and you may be banned, so be careful.\n🟢If you want your balance, it must not be less than $2 in sender /coin\n🔵To know the laws, send /rules\n⚫To change your language, send /language\n\nWe always work to serve you, and payments will be immediate if you provide good quality accounts, and you will not be paid',
        'continue_help': 'To continue, send the default account number or send /help for instructions.',
        
        # Leader management buttons
        'add_leader': '➕ Add Leader',
        'edit_leader': '✏️ Edit Leader',
        'delete_leader': '🗑️ Delete Leader',
        'show_leader_stats': '📊 Leader Statistics',
        'encrypt_leader_stats': '🔒 Encrypt Statistics',
        
        # Leader management messages
        'enter_leader_id': 'Send leader ID or username (user_id or @username):',
        'enter_leader_channel': 'Send leader channel ID (channel_id or @channel):',
        'enter_leader_name': 'Send leader name (for users):',
        'enter_leader_commission': 'Send commission per number (example: 0.03):',
        'enter_leader_wallet': 'Send leader wallet address:',
        'leader_added_success': '✅ Leader \'{name}\' added successfully!',
        'leader_edited_success': '✅ Leader data updated successfully!',
        'leader_deleted_success': '✅ Leader \'{name}\' deleted successfully!',
        'no_leaders': '❌ No leaders registered',
        'leader_not_found': '❌ Leader not found',
        'choose_leader_to_edit': 'Choose the leader to edit:',
        'choose_leader_to_delete': 'Choose the leader to delete:',
        'choose_leader_to_show_stats': 'Choose the leader to view statistics:',
        'choose_leader_to_encrypt': 'Choose the leader to reset statistics:',
        'enter_new_leader_data': 'Send new data (name, channel ID, commission, wallet address) each on a separate line:\nLeader name\nChannel ID\nCommission\nWallet address',
        'invalid_commission': '❌ Commission must be a number',
        'incomplete_data': '❌ Incomplete data',
        'leader_stats_title': '📊 Leader Statistics: {name}',
        'leader_withdrawals_count': '🔹 Number of withdrawals: {count}',
        'leader_total_withdrawn': '🔹 Total withdrawal balance: ${amount:.2f}',
        'leader_total_commission': '🔹 Total commission balance: ${amount:.2f}',
        'leader_numbers_count': '🔹 Number of received numbers: {count}',
        'leader_stats_reset': '✅ Leader \'{name}\' statistics reset successfully!',
        'leader_stats_reset_confirm': 'Do you really want to reset leader \'{name}\' statistics?',
        'leader_no_wallet': '❌ Leader not found or has no wallet address.',
        'leader_stats_your_title': '📊 Your statistics as a leader:',
        'enter_leadername': 'Please enter the LEADERNAME:',
        
        # Withdrawal messages
        'new_withdrawal_request': 'New withdrawal request',
        'your_balance_is': 'Your balance is:',
        'current_time': 'Current time:',
        'number_of_added_numbers': 'The number of added numbers:',
        'click_button_to_enter_wallet': 'Click the button below to proceed with entering your wallet address.',
        'enter_wallet_address': 'Enter Wallet Address',
        'send_withdrawal_wallet': 'Send your withdrawal wallet',
        'allowed_wallet_types': 'Allowed: BEP20, LEADERNAME, TRC20',
        'insufficient_balance': 'Your balance is insufficient to complete a withdrawal',
        'request_sent_to_owner': 'Your request has been sent to the owner',
        'payment_confirmed_successfully': 'Your payment has been confirmed successfully',
        'enter_wallet_address_type': 'Please enter the {wallet_type} wallet address:',
        'confirm_withdrawal': 'Confirm Withdrawal',
        'trx_exchange_error': "We can't get a Trx exchange address now. Please try again later.",
        'error_processing_request': 'An error occurred while processing your request. Please try later.',
    },
    'fa': {
        "maintenance_False":"غیرفعال کردن حالت نگهداری", 
        "maintenance_True":"حالت تعمیر و نگهداری را فعال کنید", 
        "spam_issue":"شماره مسدود شده است. هرزنامه رد شده است!!!!",  
        "invalid_2fa_password":"تأیید دو مرحله ای اشتباه وارد شد. اکنون دوباره امتحان کنید.",  
        "balance_added":"🎉 شماره با موفقیت اضافه شد {number} \n\nاکنون آماده دریافت شماره‌های بیشتر هستم، اگر به چیزی نیاز دارید /help ارسال کنید.", 
        'too_many_sessions': "جلسات همچنان باقی است، عملیات لغو شد. شماره را مجدداً اضافه کنید.", 
        "starting_verification": "شروع تأیید", 
        "please_wait": "لطفا کمی صبر کنید......", 
        'get_remaining_time': 'نمایش زمان باقی‌مانده', 
        "gift": "بررسی ویژه", 
        'select_language': 'زبان مورد نظر خود را انتخاب کنید:',
        'welcome': 'خوش آمدید',
        'cancel': 'لغو',
        'send_number': 'شماره را ارسال کنید.',
        'send_code': 'کد برای شماره {number} درخواست شد.\n\nاکنون کد را ارسال کنید یا "لغو" برای لغو عملیات ارسال کنید.',
        'session_added': 'تبریک! شماره {number} با موفقیت تأیید شد. مبلغ {balance} به حساب شما اضافه شد.',
        'send_password': '🔑 رمز عبور شماره {number} یا تأیید دو مرحله‌ای را وارد کنید.',
        'number_exists': 'شماره قبلاً وجود دارد.',
        'invalid_number': 'شماره نامعتبر است.',
        'invalid_code': 'کد نامعتبر است.',
        'expired_code': 'کد منقضی شده است، دوباره امتحان کنید.',
        'delete_number': 'شماره با موفقیت حذف شد.',
        'fetch_session': 'فایل جلسه را دریافت کنید',
        'no_numbers': 'شما در حال حاضر شماره‌ای ندارید.',
        'choose_number': 'در اینجا شماره‌های شما است، یکی را برای حذف انتخاب کنید.',
        'language_set': 'زبان با موفقیت انتخاب شد!',
        'add_country': 'اضافه کردن کشور',
        'country_list': 'لیست کشورها',
        'country_not_supported': 'ما در حال حاضر شماره‌ای از این کشور خریداری نمی‌کنیم.',
        'enter_country_name': 'نام کشور را وارد کنید:',
        'enter_country_code': 'کد کشور را وارد کنید:',
        'enter_country_price': 'قیمت خرید را به دلار وارد کنید:',
        'enter_hours': 'تعداد ساعت‌ها را قبل از تأیید وارد کنید:',
        'country_added': 'کشور با موفقیت اضافه شد!',
        'show_countries': 'نمایش کشور‌های ثبت شده',
        'no_countries': 'در حال حاضر هیچ کشوری ثبت نشده است.',
        'delete_country': 'حذف کشور',
        'country_deleted': 'کشور با موفقیت حذف شد!',
        'choose_country_to_delete': 'کشوری که می‌خواهید حذف کنید را انتخاب کنید:',
        'country_not_found': 'کشور یافت نشد.',
        'cancelled': 'عملیات لغو شد.',
        'confirm': 'تأیید',
        'balance': 'موجودی فعلی شما:',
        "yes": "بله",
        "no": "خیر",
        "confirm_delete": "آیا واقعاً می‌خواهید {country_name} را حذف کنید؟",
        "delete_cancelled": "حذف لغو شد.",
        "country_deleted": "{country_name} حذف شد.",
        "no_countries": "کشوری برای حذف وجود ندارد.",
        "country_not_supported": "این عملیات برای کشور شما پشتیبانی نمی‌شود.",
        'ban_user_button': 'مسدود کردن کاربر',
        'unban_user_button': 'رفع مسدودیت کاربر',
        'view_pending_numbers': 'شماره‌ها در حال بررسی هستند',
        'no_pending_numbers': 'هنوز هیچ شماره‌ای ثبت نشده است',
        "idbc": "اضافه کردن اعتبار", 
        "ax": "اعتبار رقابتی", 
        "send_country_numbers": "دریافت شماره‌های کشور",
        "send_country_code": "کد کشور را ارسال کنید",
        
        'number_added': 'شماره با موفقیت اضافه شد.\nوقتی زمان تمام شود، خواهید دید...👇',
        'end_sessions': 'باید تمام جلسات را به جز جلسه ربات پایان دهید.',
        'operation_cancelled': 'عملیات لغو شد.',
        'timeout_error': 'خطای زمان.',
        'unsupported_number': 'شماره پشتیبانی نمی‌شود.',
        'code_numbers_only': 'کد باید فقط عدد باشد.',
        'code_five_digits': 'کد باید 5 رقمی باشد.',
        'api_or_number_error': 'خطای API یا شماره اشتباه است.',
        'error_fetching_sessions': 'خطا در دریافت جلسات.',
        'sessions_correct': 'جلسات با موفقیت پایان یافت.',
        'invalid_or_expired_code': 'کد وارد شده نامعتبر یا منقضی شده است.',
        'enter_time_format': 'فرمت زمان باید به صورت زیر باشد:\nساعت\nدقیقه\nثانیه',
        'end_sessions_retry': 'جلسات را پایان داده و دوباره امتحان کنید.',
        'password_correct': 'رمز عبور صحیح وارد شد.',
        'unknown_error': 'خطای ناشناخته رخ داد.',
        'show_remaining_time': 'نمایش زمان باقی‌مانده',
        'remaining_time': 'زمان باقی‌مانده: {time} ثانیه', 
        'time_elapsed': 'زمان به پایان رسیده است',
        'number_not_found': 'شماره یافت نشد',
        'number_already_registered': '🚫 شماره {number} قبلاً ثبت شده است.',
        'number_pending_verification': '🚫 شماره {number} قبلاً ارسال شده و در فرآیند تأیید است.',
        'maintenance_mode_enabled': 'حالت تعمیر و نگهداری با موفقیت فعال شد.',
        'maintenance_mode_disabled': 'حالت تعمیر و نگهداری با موفقیت غیرفعال شد.',
        'maintenance_mode_already_enabled': 'ربات در حال حاضر در حالت تعمیر و نگهداری است.',
        'maintenance_mode_already_disabled': 'ربات در حالت تعمیر و نگهداری نیست.',
        'maintenance_mode_active': 'ربات در حال حاضر در حالت تعمیر و نگهداری است. لطفاً بعداً دوباره تلاش کنید.',
        'data_not_present': 'اطلاعات شما در پایگاه داده موجود نیست. فقط /start را ارسال کنید و دوباره تلاش کنید.',
        'no_permission': 'شما مجوز ندارید.',
        'send_user_id_ban': 'شناسه کاربری یا نام کاربری را برای مسدود کردن ارسال کنید.',
        'user_banned_success': 'کاربر {user_id} با موفقیت مسدود شد.',
        'user_already_banned': 'کاربر {user_id} قبلاً مسدود شده است.',
        'send_user_id_unban': 'شناسه کاربری یا نام کاربری را برای رفع مسدودیت ارسال کنید.',
        'user_unbanned_success': 'مسدودیت کاربر {user_id} با موفقیت لغو شد.',
        'user_not_banned': 'کاربر {user_id} مسدود نیست.',
        'enter_balance_to_add': 'چقدر می‌خواهید اعتبار اضافه کنید؟',
        'enter_balance_to_deduct': 'چقدر می‌خواهید اعتبار کم کنید؟',
        'invalid_amount': 'مبلغ نامعتبر است، لطفاً دوباره تلاش کنید.',
        'balance_added_success': '{amount} $ به اعتبار کاربر {user_id} اضافه شد.',
        'balance_deducted_success': '{amount} $ از اعتبار کاربر {user_id} کسر شد.',
        'balance_added_by_owner': 'توسط مالک اضافه شد.',
        'invalid_price': 'قیمت نامعتبر است، لطفاً دوباره تلاش کنید.',
        'invalid_format': 'فرمت نامعتبر است، لطفاً دوباره تلاش کنید.',
        'invalid_input': 'ورودی نامعتبر است، لطفاً دوباره تلاش کنید.',
        'enter_max_numbers': 'تعداد شماره‌های مورد نیاز برای خرید را وارد کنید',
        'enable_spam_check': 'آیا می‌خواهید بررسی هرزنامه را برای این کشور فعال کنید؟\nارسال: بله یا خیر',
        'timeout': 'خطای زمان.',
        'help_message': 'می‌توانید با مالک تماس بگیرید یا از یکی از گزینه‌های زیر استفاده کنید\n@Alazaizy\n⚪اگر می‌خواهید حساب اضافه کنید، من آماده دریافت آن هستم. می‌توانید آن را ارسال کنید\nتوجه: سیستم ما هر حسابی را که بازنشانی می‌کنید تأیید می‌کند و اعتبار به شما اضافه نمی‌شود و ممکن است مسدود شوید، بنابراین مراقب باشید.\n🟢اگر می‌خواهید اعتبار خود را داشته باشید، نباید کمتر از 2 دلار در فرستنده /coin باشد\n🔵برای دانستن قوانین، /rules را ارسال کنید\n⚫برای تغییر زبان خود، /language را ارسال کنید\n\nما همیشه برای خدمت به شما کار می‌کنیم و پرداخت‌ها فوری خواهد بود اگر حساب‌های با کیفیت خوب ارائه دهید و به شما پرداخت نخواهد شد',
        'continue_help': 'برای ادامه، شماره حساب پیش‌فرض را ارسال کنید یا /help را برای دستورالعمل‌ها ارسال کنید.',
        
        # دکمه‌های مدیریت رهبر
        'add_leader': '➕ افزودن رهبر',
        'edit_leader': '✏️ ویرایش رهبر',
        'delete_leader': '🗑️ حذف رهبر',
        'show_leader_stats': '📊 آمار رهبر',
        'encrypt_leader_stats': '🔒 رمزگذاری آمار',
        
        # پیام‌های مدیریت رهبر
        'enter_leader_id': 'شناسه یا نام کاربری رهبر را ارسال کنید (user_id یا @username):',
        'enter_leader_channel': 'شناسه کانال رهبر را ارسال کنید (channel_id یا @channel):',
        'enter_leader_name': 'نام رهبر را ارسال کنید (برای کاربران):',
        'enter_leader_commission': 'کمیسیون برای هر شماره را ارسال کنید (مثال: 0.03):',
        'enter_leader_wallet': 'آدرس کیف پول رهبر را ارسال کنید:',
        'leader_added_success': '✅ رهبر \'{name}\' با موفقیت اضافه شد!',
        'leader_edited_success': '✅ اطلاعات رهبر با موفقیت به‌روزرسانی شد!',
        'leader_deleted_success': '✅ رهبر \'{name}\' با موفقیت حذف شد!',
        'no_leaders': '❌ هیچ رهبری ثبت نشده است',
        'leader_not_found': '❌ رهبر یافت نشد',
        'choose_leader_to_edit': 'رهبری را که می‌خواهید ویرایش کنید انتخاب کنید:',
        'choose_leader_to_delete': 'رهبری را که می‌خواهید حذف کنید انتخاب کنید:',
        'choose_leader_to_show_stats': 'رهبری را برای مشاهده آمار انتخاب کنید:',
        'choose_leader_to_encrypt': 'رهبری را برای بازنشانی آمار انتخاب کنید:',
        'enter_new_leader_data': 'اطلاعات جدید را ارسال کنید (نام، شناسه کانال، کمیسیون، آدرس کیف پول) هر کدام در یک خط:\nنام رهبر\nشناسه کانال\nکمیسیون\nآدرس کیف پول',
        'invalid_commission': '❌ کمیسیون باید یک عدد باشد',
        'incomplete_data': '❌ اطلاعات ناقص است',
        'leader_stats_title': '📊 آمار رهبر: {name}',
        'leader_withdrawals_count': '🔹 تعداد برداشت‌ها: {count}',
        'leader_total_withdrawn': '🔹 کل موجودی برداشت: ${amount:.2f}',
        'leader_total_commission': '🔹 کل موجودی کمیسیون: ${amount:.2f}',
        'leader_numbers_count': '🔹 تعداد شماره‌های دریافت شده: {count}',
        'leader_stats_reset': '✅ آمار رهبر \'{name}\' با موفقیت بازنشانی شد!',
        'leader_stats_reset_confirm': 'آیا واقعاً می‌خواهید آمار رهبر \'{name}\' را بازنشانی کنید؟',
        'leader_no_wallet': '❌ رهبر یافت نشد یا آدرس کیف پول ندارد.',
        'leader_stats_your_title': '📊 آمار شما به عنوان رهبر:',
        'enter_leadername': 'لطفاً نام رهبر (LEADERNAME) را وارد کنید:',
        
        # پیام‌های برداشت
        'new_withdrawal_request': 'درخواست برداشت جدید',
        'your_balance_is': 'موجودی شما:',
        'current_time': 'زمان فعلی:',
        'number_of_added_numbers': 'تعداد شماره‌های اضافه شده:',
        'click_button_to_enter_wallet': 'برای ادامه، روی دکمه زیر کلیک کنید تا آدرس کیف پول خود را وارد کنید.',
        'enter_wallet_address': 'وارد کردن آدرس کیف پول',
        'send_withdrawal_wallet': 'آدرس کیف پول برداشت را ارسال کنید',
        'allowed_wallet_types': 'مجاز: BEP20, LEADERNAME, TRC20',
        'insufficient_balance': 'موجودی شما برای تکمیل برداشت کافی نیست',
        'request_sent_to_owner': 'درخواست شما به مالک ارسال شد',
        'payment_confirmed_successfully': 'پرداخت شما با موفقیت تأیید شد',
        'enter_wallet_address_type': 'لطفاً آدرس کیف پول {wallet_type} را وارد کنید:',
        'confirm_withdrawal': 'تأیید برداشت',
        'trx_exchange_error': 'در حال حاضر نمی‌توانیم آدرس مبادله TRX را دریافت کنیم. لطفاً بعداً دوباره تلاش کنید.',
        'error_processing_request': 'خطایی در پردازش درخواست شما رخ داد. لطفاً بعداً دوباره تلاش کنید.',
    },
    'ru': {
        "maintenance_False":"Отключить режим обслуживания", 
        "maintenance_True":"Включить режим обслуживания", 
        "spam_issue":"Номер заблокирован. Спам был отклонен!!!!!!", 
        "show_balance": "Показать баланс",
        "balance_info": "Будет добавлено {balance} к вашему балансу за этот номер",
        "invalid_2fa_password":"Двухфакторная аутентификация была введена неправильно. Попробуйте снова сейчас.",  
        "balance_added":"🎉 Номер успешно добавлен {number} \n\nТеперь я готов получать больше номеров, если вам что-то нужно, отправьте /help", 
        'too_many_sessions': "Все еще остаются сессии, операция отменена. Добавьте номер снова.", 
        "starting_verification": "Начало проверки", 
        "please_wait": "Пожалуйста, подождите немного......", 
        'get_remaining_time': 'Показать оставшееся время', 
        "gift": "Особый осмотр", 
        'select_language': 'Пожалуйста, выберите предпочитаемый язык.',
        'welcome': 'Добро пожаловать',
        'cancel': 'Отмена',
        'send_number': 'Отправьте номер.',
        'send_code': 'Код запрошен для номера {number}.\n\nОтправьте код сейчас или отправьте "отмена" для отмены операции.',
        'session_added': 'Поздравляем! Номер {number} был успешно подтвержден. Баланс {balance} был добавлен на ваш счет.',
        'send_password': '🔑 Введите пароль для номера {number} или двухфакторную аутентификацию.',
        'number_exists': 'Номер уже существует.',
        'invalid_number': 'Неверный номер.',
        'invalid_code': 'Неверный код.',
        'expired_code': 'Код истек, попробуйте снова.',
        'delete_number': 'Номер успешно удален.',
        'fetch_session': 'Получить файл сессии',
        'no_numbers': 'У вас в настоящее время нет номеров.',
        'choose_number': 'Вот ваши номера, выберите один для удаления',
        'language_set': 'Язык был успешно выбран!',
        'add_country': 'Добавить страну',
        'country_list': 'Список стран',
        'country_not_supported': 'Мы в настоящее время не покупаем номера из этой страны.',
        'enter_country_name': 'Введите название страны:',
        'enter_country_code': 'Введите код страны:',
        'enter_country_price': 'Введите цену покупки в долларах:',
        'enter_hours': 'Введите количество часов до проверки:',
        'country_added': 'Страна успешно добавлена!',
        'show_countries': 'Показать зарегистрированные страны',
        'no_countries': 'В настоящее время нет зарегистрированных стран.',
        'delete_country': 'Удалить страну',
        'country_deleted': 'Страна успешно удалена!',
        'choose_country_to_delete': 'Выберите страну для удаления:',
        'country_not_found': 'Страна не найдена.',
        'cancelled': 'Операция отменена.',
        'confirm': 'Подтвердить',
        'balance': 'Ваш текущий баланс:',
        "yes": "Да",
        "no": "Нет",
        "confirm_delete": "Вы действительно хотите удалить {country_name}?",
        "delete_cancelled": "Удаление отменено.",
        "country_deleted": "{country_name} был удален.",
        "no_countries": "Нет стран для удаления.",
        "country_not_supported": "Это действие не поддерживается для вашей страны.",
        'ban_user_button': 'Заблокировать пользователя',
        'unban_user_button': 'Разблокировать пользователя',
        'view_pending_numbers': 'Номера проверяются',
        'no_pending_numbers': 'Пока не зарегистрировано ни одного номера',
        "idbc": "Добавить кредит", 
        "ax": "Конкурентный кредит", 
        "send_country_numbers": "Получить номера страны",
        "send_country_code": "Отправить код страны",
        
        'number_added': 'Номер успешно добавлен.\nКогда время истечет, вы получите... 👇',
        'end_sessions': 'Вам нужно завершить все сессии, кроме сессии бота.',
        'operation_cancelled': 'Операция отменена.',
        'timeout_error': 'Ошибка таймаута.',
        'unsupported_number': 'Неподдерживаемый номер.',
        'code_numbers_only': 'Код должен состоять только из цифр.',
        'code_five_digits': 'Код должен состоять из 5 цифр.',
        'api_or_number_error': 'Ошибка API или номер неверен.',
        'error_fetching_sessions': 'Ошибка при получении сессий.',
        'sessions_correct': 'Сессии успешно завершены.',
        'invalid_or_expired_code': 'Неверный или истекший код.',
        'enter_time_format': 'Формат времени должен быть:\nЧасы\nМинуты\nСекунды',
        'end_sessions_retry': 'Завершите сессии и попробуйте снова.',
        'password_correct': 'Правильный пароль введен.',
        'unknown_error': 'Произошла неизвестная ошибка.',
        'show_remaining_time': 'Показать оставшееся время',
        'remaining_time': 'Оставшееся время: {time} секунд', 
        'time_elapsed': 'Время истекло',
        'number_not_found': 'Номер не найден',
        'number_already_registered': '🚫 Номер {number} уже был зарегистрирован.',
        'number_pending_verification': '🚫 Номер {number} был отправлен ранее и находится в процессе проверки.',
        'account_invalid': 'Аккаунт недействителен',
        'maintenance_mode_enabled': 'Режим обслуживания был успешно включен.',
        'maintenance_mode_disabled': 'Режим обслуживания был успешно отключен.',
        'maintenance_mode_already_enabled': 'Бот уже находится в режиме обслуживания.',
        'maintenance_mode_already_disabled': 'Бот не находится в режиме обслуживания.',
        'maintenance_mode_active': 'Бот в настоящее время находится в режиме обслуживания. Пожалуйста, попробуйте позже.',
        'data_not_present': 'Ваши данные отсутствуют в базе данных. Просто отправьте /start и попробуйте снова.',
        'no_permission': 'У вас нет разрешения.',
        'send_user_id_ban': 'Отправьте ID пользователя или имя пользователя для блокировки.',
        'user_banned_success': 'Пользователь {user_id} был успешно заблокирован.',
        'user_already_banned': 'Пользователь {user_id} уже заблокирован.',
        'send_user_id_unban': 'Отправьте ID пользователя или имя пользователя для разблокировки.',
        'user_unbanned_success': 'Пользователь {user_id} был успешно разблокирован.',
        'user_not_banned': 'Пользователь {user_id} не заблокирован.',
        'enter_balance_to_add': 'Сколько баланса вы хотите добавить?',
        'enter_balance_to_deduct': 'Сколько баланса вы хотите вычесть?',
        'invalid_amount': 'Неверная сумма, пожалуйста, попробуйте снова.',
        'balance_added_success': 'Добавлено {amount} $ к балансу пользователя {user_id}.',
        'balance_deducted_success': 'Вычтено {amount} $ из баланса пользователя {user_id}.',
        'balance_added_by_owner': 'Добавлено владельцем.',
        'invalid_price': 'Неверная цена, пожалуйста, попробуйте снова.',
        'invalid_format': 'Неверный формат, пожалуйста, попробуйте снова.',
        'invalid_input': 'Неверный ввод, пожалуйста, попробуйте снова.',
        'enter_max_numbers': 'Введите количество номеров для покупки',
        'enable_spam_check': 'Хотите ли вы включить проверку спама для этой страны?\nОтправьте: Да или Нет',
        'timeout': 'Ошибка таймаута.',
        'help_message': 'Вы можете связаться с владельцем или использовать один из вариантов ниже\n@Alazaizy\n⚪Если вы хотите добавить аккаунт, я готов его получить. Вы можете отправить его\nПримечание: Наша система проверит любой аккаунт, который вы сбросите, и баланс не будет добавлен вам, и вы можете быть заблокированы, поэтому будьте осторожны.\n🟢Если вы хотите свой баланс, он не должен быть менее 2 долларов в отправителе /coin\n🔵Чтобы узнать законы, отправьте /rules\n⚫Чтобы изменить язык, отправьте /language\n\nМы всегда работаем, чтобы служить вам, и платежи будут немедленными, если вы предоставите качественные аккаунты, и вам не будет заплачено',
        'continue_help': 'Чтобы продолжить, отправьте номер счета по умолчанию или отправьте /help для инструкций.',
        
        # Кнопки управления лидерами
        'add_leader': '➕ Добавить лидера',
        'edit_leader': '✏️ Редактировать лидера',
        'delete_leader': '🗑️ Удалить лидера',
        'show_leader_stats': '📊 Статистика лидера',
        'encrypt_leader_stats': '🔒 Зашифровать статистику',
        
        # Сообщения управления лидерами
        'enter_leader_id': 'Отправьте ID лидера или имя пользователя (user_id или @username):',
        'enter_leader_channel': 'Отправьте ID канала лидера (channel_id или @channel):',
        'enter_leader_name': 'Отправьте имя лидера (для пользователей):',
        'enter_leader_commission': 'Отправьте комиссию за каждый номер (пример: 0.03):',
        'enter_leader_wallet': 'Отправьте адрес кошелька лидера:',
        'leader_added_success': '✅ Лидер \'{name}\' успешно добавлен!',
        'leader_edited_success': '✅ Данные лидера успешно обновлены!',
        'leader_deleted_success': '✅ Лидер \'{name}\' успешно удален!',
        'no_leaders': '❌ Нет зарегистрированных лидеров',
        'leader_not_found': '❌ Лидер не найден',
        'choose_leader_to_edit': 'Выберите лидера для редактирования:',
        'choose_leader_to_delete': 'Выберите лидера для удаления:',
        'choose_leader_to_show_stats': 'Выберите лидера для просмотра статистики:',
        'choose_leader_to_encrypt': 'Выберите лидера для сброса статистики:',
        'enter_new_leader_data': 'Отправьте новые данные (имя, ID канала, комиссия, адрес кошелька) каждое с новой строки:\nИмя лидера\nID канала\nКомиссия\nАдрес кошелька',
        'invalid_commission': '❌ Комиссия должна быть числом',
        'incomplete_data': '❌ Неполные данные',
        'leader_stats_title': '📊 Статистика лидера: {name}',
        'leader_withdrawals_count': '🔹 Количество выводов: {count}',
        'leader_total_withdrawn': '🔹 Общий баланс выводов: ${amount:.2f}',
        'leader_total_commission': '🔹 Общий баланс комиссии: ${amount:.2f}',
        'leader_numbers_count': '🔹 Количество полученных номеров: {count}',
        'leader_stats_reset': '✅ Статистика лидера \'{name}\' успешно сброшена!',
        'leader_stats_reset_confirm': 'Вы действительно хотите сбросить статистику лидера \'{name}\'?',
        'leader_no_wallet': '❌ Лидер не найден или не имеет адреса кошелька.',
        'leader_stats_your_title': '📊 Ваша статистика как лидера:',
        'enter_leadername': 'Пожалуйста, введите имя лидера (LEADERNAME):',
        
        # Сообщения о выводе
        'new_withdrawal_request': 'Новый запрос на вывод',
        'your_balance_is': 'Ваш баланс:',
        'current_time': 'Текущее время:',
        'number_of_added_numbers': 'Количество добавленных номеров:',
        'click_button_to_enter_wallet': 'Нажмите кнопку ниже, чтобы продолжить ввод адреса кошелька.',
        'enter_wallet_address': 'Ввести адрес кошелька',
        'send_withdrawal_wallet': 'Отправьте адрес кошелька для вывода',
        'allowed_wallet_types': 'Разрешено: BEP20, LEADERNAME, TRC20',
        'insufficient_balance': 'Ваш баланс недостаточен для завершения вывода',
        'request_sent_to_owner': 'Ваш запрос отправлен владельцу',
        'payment_confirmed_successfully': 'Ваш платеж успешно подтвержден',
        'enter_wallet_address_type': 'Пожалуйста, введите адрес кошелька {wallet_type}:',
        'confirm_withdrawal': 'Подтвердить вывод',
        'trx_exchange_error': 'Мы не можем получить адрес обмена TRX сейчас. Пожалуйста, попробуйте позже.',
        'error_processing_request': 'Произошла ошибка при обработке вашего запроса. Пожалуйста, попробуйте позже.',
    },
}
